let episodes = `[{"episodeName":"Welcome to the Hellmouth","episodeDate":"10-Mar-97"},
{"episodeName":"The Harvest","episodeDate":"10-Mar-97"},
{"episodeName":"Witch","episodeDate":"17-Mar-97"},
{"episodeName":"Teacher's Pet","episodeDate":"24-Mar-97"},
{"episodeName":"Never Kill a Boy on the First Date","episodeDate":"31-Mar-97"},
{"episodeName":"The Pack","episodeDate":"07-Apr-97"},
{"episodeName":"Angel","episodeDate":"14-Apr-97"},
{"episodeName":"I, Robot... You, Jane","episodeDate":"28-Apr-97"},
{"episodeName":"The Puppet Show","episodeDate":"05-May-97"},
{"episodeName":"Nightmares","episodeDate":"12-May-97"},
{"episodeName":"Out of Mind, Out of Sight","episodeDate":"19-May-97"},
{"episodeName":"Prophecy Girl","episodeDate":"02-Jun-97"},
{"episodeName":"When She Was Bad","episodeDate":"15-Sep-97"},
{"episodeName":"Some Assembly Required","episodeDate":"22-Sep-97"},
{"episodeName":"School Hard","episodeDate":"29-Sep-97"},
{"episodeName":"Inca Mummy Girl","episodeDate":"06-Oct-97"},
{"episodeName":"Reptile Boy","episodeDate":"13-Oct-97"},
{"episodeName":"Halloween","episodeDate":"27-Oct-97"},
{"episodeName":"Lie to Me","episodeDate":"03-Nov-97"},
{"episodeName":"The Dark Age","episodeDate":"10-Nov-97"},
{"episodeName":"What's My Line (Part 1)","episodeDate":"17-Nov-97"},
{"episodeName":"What's My Line (Part 2)","episodeDate":"24-Nov-97"},
{"episodeName":"Ted","episodeDate":"08-Dec-97"},
{"episodeName":"Bad Eggs","episodeDate":"12-Jan-98"},
{"episodeName":"Surprise","episodeDate":"19-Jan-98"},
{"episodeName":"Innocence","episodeDate":"20-Jan-98"},
{"episodeName":"Phases","episodeDate":"27-Jan-98"},
{"episodeName":"Bewitched, Bothered and Bewildered","episodeDate":"10-Feb-98"},
{"episodeName":"Passion","episodeDate":"24-Feb-98"},
{"episodeName":"Killed by Death","episodeDate":"03-Mar-98"},
{"episodeName":"I Only Have Eyes for You","episodeDate":"28-Apr-98"},
{"episodeName":"Go Fish","episodeDate":"05-May-98"},
{"episodeName":"Becoming (Part 1)","episodeDate":"12-May-98"},
{"episodeName":"Becoming (Part 2)","episodeDate":"19-May-98"},
{"episodeName":"Anne","episodeDate":"29-Sep-98"},
{"episodeName":"Dead Man's Party","episodeDate":"06-Oct-98"},
{"episodeName":"Faith, Hope & Trick","episodeDate":"13-Oct-98"},
{"episodeName":"Beauty and the Beasts","episodeDate":"20-Oct-98"},
{"episodeName":"Homecoming","episodeDate":"03-Nov-98"},
{"episodeName":"Band Candy","episodeDate":"10-Nov-98"},
{"episodeName":"Revelations","episodeDate":"17-Nov-98"},
{"episodeName":"Lovers Walk","episodeDate":"24-Nov-98"},
{"episodeName":"The Wish","episodeDate":"08-Dec-98"},
{"episodeName":"Amends","episodeDate":"15-Dec-98"},
{"episodeName":"Gingerbread","episodeDate":"12-Jan-99"},
{"episodeName":"Helpless","episodeDate":"19-Jan-99"},
{"episodeName":"The Zeppo","episodeDate":"26-Jan-99"},
{"episodeName":"Bad Girls","episodeDate":"09-Feb-99"},
{"episodeName":"Consequences","episodeDate":"16-Feb-99"},
{"episodeName":"Doppelgangland","episodeDate":"23-Feb-99"},
{"episodeName":"Enemies","episodeDate":"16-Mar-99"},
{"episodeName":"Earshot","episodeDate":"21-Sep-99"},
{"episodeName":"Choices","episodeDate":"04-May-99"},
{"episodeName":"The Prom","episodeDate":"11-May-99"},
{"episodeName":"Graduation Day (Part 1)","episodeDate":"18-May-99"},
{"episodeName":"Graduation Day (Part 2)","episodeDate":"May 24, 1999 (Canada) July 13, 1999 (USA)"},
{"episodeName":"The Freshman","episodeDate":"05-Oct-99"},
{"episodeName":"Living Conditions","episodeDate":"12-Oct-99"},
{"episodeName":"The Harsh Light of Day","episodeDate":"19-Oct-99"},
{"episodeName":"Fear, Itself","episodeDate":"26-Oct-99"},
{"episodeName":"Beer Bad","episodeDate":"02-Nov-99"},
{"episodeName":"Wild at Heart","episodeDate":"09-Nov-99"},
{"episodeName":"The Initiative","episodeDate":"16-Nov-99"},
{"episodeName":"Pangs","episodeDate":"23-Nov-99"},
{"episodeName":"Something Blue","episodeDate":"30-Nov-99"},
{"episodeName":"Hush","episodeDate":"14-Dec-99"},
{"episodeName":"Doomed","episodeDate":"18-Jan-00"},
{"episodeName":"A New Man","episodeDate":"25-Jan-00"},
{"episodeName":"The I in Team","episodeDate":"08-Feb-00"},
{"episodeName":"Goodbye Iowa","episodeDate":"15-Feb-00"},
{"episodeName":"This Year's Girl","episodeDate":"22-Feb-00"},
{"episodeName":"Who Are You","episodeDate":"29-Feb-00"},
{"episodeName":"Superstar","episodeDate":"04-Apr-00"},
{"episodeName":"Where the Wild Things Are","episodeDate":"25-Apr-00"},
{"episodeName":"New Moon Rising","episodeDate":"02-May-00"},
{"episodeName":"The Yoko Factor","episodeDate":"09-May-00"},
{"episodeName":"Primeval","episodeDate":"16-May-00"},
{"episodeName":"Restless","episodeDate":"23-May-00"},
{"episodeName":"Buffy vs. Dracula","episodeDate":"26-Sep-00"},
{"episodeName":"Real Me","episodeDate":"03-Oct-00"},
{"episodeName":"The Replacement","episodeDate":"10-Oct-00"},
{"episodeName":"Out of My Mind","episodeDate":"17-Oct-00"},
{"episodeName":"No Place Like Home","episodeDate":"24-Oct-00"},
{"episodeName":"Family","episodeDate":"07-Nov-00"},
{"episodeName":"Fool for Love","episodeDate":"14-Nov-00"},
{"episodeName":"Shadow","episodeDate":"21-Nov-00"},
{"episodeName":"Listening to Fear","episodeDate":"28-Nov-00"},
{"episodeName":"Into the Woods","episodeDate":"19-Dec-00"},
{"episodeName":"Triangle","episodeDate":"09-Jan-01"},
{"episodeName":"Checkpoint","episodeDate":"23-Jan-01"},
{"episodeName":"Blood Ties","episodeDate":"06-Feb-01"},
{"episodeName":"Crush","episodeDate":"13-Feb-01"},
{"episodeName":"I Was Made to Love You","episodeDate":"20-Feb-01"},
{"episodeName":"The Body","episodeDate":"27-Feb-01"},
{"episodeName":"Forever","episodeDate":"17-Apr-01"},
{"episodeName":"Intervention","episodeDate":"24-Apr-01"},
{"episodeName":"Tough Love","episodeDate":"01-May-01"},
{"episodeName":"Spiral","episodeDate":"08-May-01"},
{"episodeName":"The Weight of the World","episodeDate":"15-May-01"},
{"episodeName":"The Gift","episodeDate":"22-May-01"},
{"episodeName":"Bargaining (Part 1)","episodeDate":"02-Oct-01"},
{"episodeName":"Bargaining (Part 2)","episodeDate":"02-Oct-01"},
{"episodeName":"After Life","episodeDate":"09-Oct-01"},
{"episodeName":"Flooded","episodeDate":"16-Oct-01"},
{"episodeName":"Life Serial","episodeDate":"23-Oct-01"},
{"episodeName":"All the Way","episodeDate":"30-Oct-01"},
{"episodeName":"Once More, with Feeling","episodeDate":"06-Nov-01"},
{"episodeName":"Tabula Rasa","episodeDate":"13-Nov-01"},
{"episodeName":"Smashed","episodeDate":"20-Nov-01"},
{"episodeName":"Wrecked","episodeDate":"27-Nov-01"},
{"episodeName":"Gone","episodeDate":"08-Jan-02"},
{"episodeName":"Doublemeat Palace","episodeDate":"29-Jan-02"},
{"episodeName":"Dead Things","episodeDate":"05-Feb-02"},
{"episodeName":"As You Were","episodeDate":"26-Feb-02"},
{"episodeName":"Hell's Bells","episodeDate":"05-Mar-02"},
{"episodeName":"Normal Again","episodeDate":"12-Mar-02"},
{"episodeName":"Entropy","episodeDate":"30-Apr-02"},
{"episodeName":"Seeing Red","episodeDate":"07-May-02"},
{"episodeName":"Villains","episodeDate":"14-May-02"},
{"episodeName":"Two to Go","episodeDate":"21-May-02"},
{"episodeName":"Grave","episodeDate":"21-May-02"},
{"episodeName":"Lessons","episodeDate":"24-Sep-02"},
{"episodeName":"Beneath You","episodeDate":"01-Oct-02"},
{"episodeName":"Same Time, Same Place","episodeDate":"08-Oct-02"},
{"episodeName":"Help","episodeDate":"15-Oct-02"},
{"episodeName":"Selfless","episodeDate":"22-Oct-02"},
{"episodeName":"Him","episodeDate":"05-Nov-02"},
{"episodeName":"Conversations with Dead People","episodeDate":"12-Nov-02"},
{"episodeName":"Sleeper","episodeDate":"19-Nov-02"},
{"episodeName":"Never Leave Me","episodeDate":"26-Nov-02"},
{"episodeName":"Bring on the Night","episodeDate":"17-Dec-02"},
{"episodeName":"Showtime","episodeDate":"07-Jan-03"},
{"episodeName":"Potential","episodeDate":"21-Jan-03"},
{"episodeName":"The Killer in Me","episodeDate":"04-Feb-03"},
{"episodeName":"First Date","episodeDate":"11-Feb-03"},
{"episodeName":"Get It Done","episodeDate":"18-Feb-03"},
{"episodeName":"Storyteller","episodeDate":"25-Feb-03"},
{"episodeName":"Lies My Parents Told Me","episodeDate":"25-Mar-03"},
{"episodeName":"Dirty Girls","episodeDate":"15-Apr-03"},
{"episodeName":"Empty Places","episodeDate":"29-Apr-03"},
{"episodeName":"Touched","episodeDate":"06-May-03"},
{"episodeName":"End of Days","episodeDate":"13-May-03"},
{"episodeName":"Chosen","episodeDate":"20-May-03"}]`


function ageCalculate(){
    var date = document.getElementById("date").value;
    var month = document.getElementById("month").value;
    var year = document.getElementById("year").value;
    
    var formattedDate = 
    console.log(formattedDate);
};


const obj = JSON.parse(companies);
let test = obj.find(test => test.rating === "4.3");
console.log(obj);